CREATE USER 'dba'@'localhost' IDENTIFIED BY '999';
GRANT ALL PRIVILEGES ON *.* TO 'dba'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE USER 'dba'@'%' IDENTIFIED BY '999';
GRANT ALL PRIVILEGES ON *.* TO 'dba'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;