services:
  mysql:
    image: mysql:latest
    container_name: app
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: 999
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dba.sql:/docker-entrypoint-initdb.d/dba.sql

volumes:
  mysql-data:
